import Link from "next/link";
import { getServerSession } from "@/lib/supabase/server";
import { listDocuments } from "@/lib/api/backend";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

type PageProps = {
  params: { repoId: string };
  searchParams?: { org_id?: string };
};

export default async function RepoDocsPage({ params }: PageProps) {
  const session = await getServerSession();
  if (!session?.access_token) {
    return null;
  }
  const token = session.access_token;
  const repoId = Number(params.repoId);

  const docsResp = await listDocuments(repoId, token);
  const docs = docsResp.documents || [];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Repository Docs</h1>
          <p className="text-mutedForeground">View generated documentation for this repository.</p>
        </div>
        <Link href="/dashboard/repos">
          <Button variant="outline">Back to repos</Button>
        </Link>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Documents</CardTitle>
          <CardDescription>Markdown files generated by the worker.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-2">
          {docs.length === 0 ? (
            <p className="text-sm text-mutedForeground">No documents yet. Trigger a sync and check back.</p>
          ) : (
            <ul className="space-y-2">
              {docs.map((doc) => (
                <li key={doc.id} className="flex items-center justify-between border rounded-md px-3 py-2">
                  <div className="font-mono text-sm">{doc.file_path}</div>
                  <Link href={`/dashboard/docs/${doc.id}`}>
                    <Button size="sm" variant="outline">
                      Open
                    </Button>
                  </Link>
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

