import Link from "next/link";
import { getServerSession } from "@/lib/supabase/server";
import { listDocuments } from "@/lib/api/backend";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Table, TBody, TD, TH, THead, TR } from "@/components/ui/table";
import { FileText, Eye, ChevronLeft, Calendar } from "lucide-react";

type PageProps = {
  params: { repoId: string };
  searchParams?: { org_id?: string };
};

export default async function RepoDocsPage({ params, searchParams }: PageProps) {
  const session = await getServerSession();
  if (!session?.access_token) {
    return null;
  }
  const token = session.access_token;
  const repoId = Number(params.repoId);

  const docsResp = await listDocuments(repoId, token);
  const docs = docsResp.documents || [];

  const backHref = searchParams?.org_id ? `/dashboard/repos?org_id=${encodeURIComponent(searchParams.org_id)}` : "/dashboard/repos";

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
            <Link href={backHref}>
              <Button variant="ghost" size="icon">
                  <ChevronLeft className="h-4 w-4" />
              </Button>
            </Link>
            <div>
                <h1 className="text-2xl font-semibold">Repository Docs</h1>
                <p className="text-mutedForeground">View generated documentation for this repository.</p>
            </div>
        </div>
        <Link href={backHref}>
          <Button variant="outline">Back to repos</Button>
        </Link>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Generated Documents
          </CardTitle>
          <CardDescription>
             These documents were automatically generated by ArchTruth agents.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {docs.length === 0 ? (
             <div className="flex flex-col items-center justify-center py-12 text-center">
                 <div className="bg-muted p-4 rounded-full mb-4">
                     <FileText className="h-8 w-8 text-mutedForeground" />
                 </div>
                 <h3 className="text-lg font-medium">No documents found</h3>
                 <p className="text-mutedForeground max-w-sm mt-2">
                     Trigger a sync from the repositories page to generate documentation for this repo.
                 </p>
                 <Link href={backHref} className="mt-4">
                     <Button>Go to Repositories</Button>
                 </Link>
             </div>
          ) : (
            <Table>
                <THead>
                    <TR>
                        <TH>File Path</TH>
                        <TH>Last Updated</TH>
                        <TH className="text-right">Action</TH>
                    </TR>
                </THead>
                <TBody>
                    {docs.map((doc) => (
                        <TR key={doc.id}>
                            <TD className="font-mono text-sm font-medium">
                                <div className="flex items-center gap-2">
                                    <FileText className="h-4 w-4 text-primary" />
                                    {doc.file_path}
                                </div>
                            </TD>
                            <TD className="text-mutedForeground text-sm">
                                <div className="flex items-center gap-2">
                                    <Calendar className="h-3 w-3" />
                                    {doc.updated_at ? new Date(doc.updated_at).toLocaleDateString() : "-"}
                                </div>
                            </TD>
                            <TD className="text-right">
                                <Link href={`/dashboard/docs/${doc.id}`}>
                                    <Button size="sm" variant="secondary">
                                        <Eye className="h-3 w-3 mr-2" />
                                        View
                                    </Button>
                                </Link>
                            </TD>
                        </TR>
                    ))}
                </TBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
